### ISSUE TITLE
configure https

### ISSUE THREAD

**Issue by daveschafer** [vialink/viacrypt#10]
I am trying to configure the viacrypt server to listen to https and using a letsencrypt certificate.
I configured it according to the official github readme: https://gist.github.com/davestevens/c9e437afbb41c1d5c3ab

I'm struggling a bit at the 

> https.createServer(options, function (req, res) {

 part... I'm not sure where to put this and how exactly to configure the NodeJS Webserver to listen to https.
Do you have any tips for me, where I should configure https?

**Comment by msbrogli** [comment]
We have configured a webserver on top of ViaCRYPT. You may use either nginx or haproxy.
